blank_issues_enabled: false
contact_links:
  - name: GoDMC2 Wiki
    url: https://github.com/genetics-of-dna-methylation-consortium/godmc_phase2/wiki
    about: Please read the documentation here.
  - name: GoDMC2 Workflow Chart
    url: https://github.com/genetics-of-dna-methylation-consortium/godmc_phase2/wiki/Script-Flowchart
    about: Please go through the workflow here.
  - name: GoDMC2 Support
    url: https://github.com/genetics-of-dna-methylation-consortium/godmc_phase2/discussions
    about: Please ask and answer questions here.
